import{activities}from'./activities.js';
const cards=document.querySelector('#cards'),search=document.querySelector('#search'),domain=document.querySelector('#domain'),format=document.querySelector('#format'),level=document.querySelector('#level'),dialog=document.querySelector('#activityDialog'),content=document.querySelector('#dialogContent');
const uniq=k=>[...new Set(activities.map(a=>a[k]))].sort();
uniq('domain').forEach(v=>domain.insertAdjacentHTML('beforeend',`<option>${v}</option>`));uniq('format').forEach(v=>format.insertAdjacentHTML('beforeend',`<option>${v}</option>`));
document.querySelector('#count').textContent=activities.length;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function filtered(){const q=search.value.trim().toLowerCase();return activities.filter(a=>{const hay=[a.title,a.domain,a.objective,...a.tags].join(' ').toLowerCase();return(!q||hay.includes(q))&&(domain.value==='all'||a.domain===domain.value)&&(format.value==='all'||a.format===format.value)&&(level.value==='all'||a.level===level.value)})}
function render(){const list=filtered();document.querySelector('#resultCount').textContent=`${list.length} activite${list.length>1?'s':''}`;cards.innerHTML=list.map(a=>`<article class="card"><span class="badge">${esc(a.domain)}</span><h3>${esc(a.title)}</h3><p>${esc(a.objective)}</p><div class="meta"><span>${esc(a.format)}</span><span>${esc(a.level)}</span><span>${a.duration} min</span></div><button data-id="${a.id}">Ouvrir la fiche</button></article>`).join('')||'<p>Aucune activite ne correspond a ces criteres.</p>'}
function openActivity(id){const a=activities.find(x=>x.id===id);if(!a)return;content.innerHTML=`<div class="detail"><p class="eyebrow">${esc(a.domain)} · ${esc(a.format)} · ${a.duration} MIN</p><h2>${esc(a.title)}</h2><p>${esc(a.objective)}</p><div class="detail-grid"><section class="panel"><h3>Fiche apprenant</h3><h4>Situation</h4><p>${esc(a.situation)}</p><h4>Consignes</h4><ol>${a.instructions.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><div class="template"><h4>Template de reponse</h4><table><thead><tr>${a.template.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody><tr>${a.template.map(()=>'<td></td>').join('')}</tr><tr>${a.template.map(()=>'<td></td>').join('')}</tr><tr>${a.template.map(()=>'<td></td>').join('')}</tr></tbody></table></div></section><section class="panel formateur"><h3>Fiche formateur</h3><h4>Reponse attendue</h4><p>${esc(a.expected)}</p><h4>Debrief</h4><ul>${a.debrief.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h4>Objectif pedagogique</h4><p>${esc(a.objective)}</p></section></div></div>`;dialog.showModal()}
[search,domain,format,level].forEach(el=>el.addEventListener(el===search?'input':'change',render));cards.addEventListener('click',e=>{const b=e.target.closest('button[data-id]');if(b)openActivity(b.dataset.id)});dialog.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});render();